export const initialMockData = {
  // Public Courses Catalog
  courses: [
    {
      id: 'c101',
      code: 'CS-301',
      name: 'Advanced Data Structures & Algorithms',
      department: 'Computer Science',
      credits: 4,
      instructor: 'Dr. Sarah Jenkins',
      level: 'Undergraduate',
      schedule: 'Mon, Wed, Fri (10:00 AM - 11:30 AM)',
      enrolledCount: 42,
      maxCapacity: 50,
      description: 'Master advanced algorithmic techniques, graph theory, dynamic programming, and complexity analysis with hands-on lab sessions.',
      prerequisites: 'CS-201 Data Structures',
      status: 'Active',
    },
    {
      id: 'c102',
      code: 'CS-305',
      name: 'Applied Machine Learning & Data Mining',
      department: 'Computer Science',
      credits: 4,
      instructor: 'Prof. David Miller',
      level: 'Undergraduate',
      schedule: 'Tue, Thu (02:00 PM - 04:00 PM)',
      enrolledCount: 38,
      maxCapacity: 45,
      description: 'Practical exploration of supervised and unsupervised machine learning algorithms, model evaluation, neural networks, and feature engineering.',
      prerequisites: 'CS-105 Calculus & Statistics',
      status: 'Active',
    },
    {
      id: 'c103',
      code: 'MATH-202',
      name: 'Discrete Mathematics & Linear Algebra',
      department: 'Mathematics',
      credits: 3,
      instructor: 'Dr. Robert Vance',
      level: 'Undergraduate',
      schedule: 'Mon, Wed (01:00 PM - 02:30 PM)',
      enrolledCount: 48,
      maxCapacity: 50,
      description: 'Matrix operations, vector spaces, logic, combinatorics, and graph theory applied to modern computing architectures.',
      prerequisites: 'MATH-101 Engineering Math',
      status: 'Active',
    },
    {
      id: 'c104',
      code: 'SE-401',
      name: 'Software Architecture & Cloud Systems',
      department: 'Software Engineering',
      credits: 3,
      instructor: 'Prof. Elena Rostova',
      level: 'Undergraduate',
      schedule: 'Tue, Fri (09:00 AM - 10:30 AM)',
      enrolledCount: 35,
      maxCapacity: 40,
      description: 'Microservices architecture, distributed database systems, cloud deployment pipelines, CI/CD, and system design patterns.',
      prerequisites: 'SE-301 Software Design',
      status: 'Active',
    },
    {
      id: 'c105',
      code: 'AI-402',
      name: 'Natural Language Processing & LLMs',
      department: 'Artificial Intelligence',
      credits: 4,
      instructor: 'Dr. Alan Turing',
      level: 'Postgraduate',
      schedule: 'Wed, Fri (03:00 PM - 05:00 PM)',
      enrolledCount: 28,
      maxCapacity: 35,
      description: 'Deep learning for text processing, transformer models, attention mechanisms, vector databases, and fine-tuning techniques.',
      prerequisites: 'CS-305 Machine Learning',
      status: 'Active',
    },
  ],

  // Users Roster
  students: [
    {
      id: 'std_101',
      name: 'Alex Mercer',
      email: 'alex.mercer@edupulse.edu',
      rollNo: '2026-CS-042',
      department: 'Computer Science',
      semester: 6,
      cgpa: 3.42,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'Active',
      academicRisk: 'Medium',
      weakSubject: 'Mathematics',
      phone: '+1 (555) 234-5678',
      guardianName: 'Richard Mercer',
      guardianPhone: '+1 (555) 876-5432',
    },
    {
      id: 'std_102',
      name: 'Sophia Patel',
      email: 'sophia.patel@edupulse.edu',
      rollNo: '2026-CS-018',
      department: 'Computer Science',
      semester: 6,
      cgpa: 3.91,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      status: 'Active',
      academicRisk: 'Low',
      weakSubject: 'None',
      phone: '+1 (555) 345-6789',
      guardianName: 'Aarav Patel',
      guardianPhone: '+1 (555) 987-6543',
    },
    {
      id: 'std_103',
      name: 'Marcus Vance',
      email: 'marcus.vance@edupulse.edu',
      rollNo: '2026-CS-089',
      department: 'Computer Science',
      semester: 6,
      cgpa: 2.35,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'At Risk',
      academicRisk: 'High',
      weakSubject: 'Discrete Mathematics',
      phone: '+1 (555) 456-7890',
      guardianName: 'Laura Vance',
      guardianPhone: '+1 (555) 098-7654',
    },
  ],

  teachers: [
    {
      id: 'tch_201',
      name: 'Dr. Sarah Jenkins',
      email: 'sarah.jenkins@edupulse.edu',
      department: 'Computer Science',
      designation: 'Associate Professor',
      coursesAssigned: ['CS-301', 'CS-305'],
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    {
      id: 'tch_202',
      name: 'Dr. Robert Vance',
      email: 'robert.vance@edupulse.edu',
      department: 'Mathematics',
      designation: 'Professor & HOD',
      coursesAssigned: ['MATH-202'],
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
  ],

  // Student Attendance Logs (Alex Mercer std_101)
  attendance: [
    { courseId: 'c101', courseName: 'CS-301 Algorithms', attended: 26, total: 30, percentage: 86.6, status: 'Good' },
    { courseId: 'c102', courseName: 'CS-305 Machine Learning', attended: 24, total: 28, percentage: 85.7, status: 'Good' },
    { courseId: 'c103', courseName: 'MATH-202 Discrete Math', attended: 18, total: 26, percentage: 69.2, status: 'Warning' },
    { courseId: 'c104', courseName: 'SE-401 Software Arch', attended: 28, total: 30, percentage: 93.3, status: 'Excellent' },
  ],

  // Student Assignments
  assignments: [
    {
      id: 'asg-1',
      title: 'Graph Traversal & BFS/DFS Implementation',
      courseCode: 'CS-301',
      courseName: 'CS-301 Algorithms',
      dueDate: '2026-08-20',
      totalPoints: 100,
      earnedPoints: 88,
      status: 'Graded',
      submittedAt: '2026-08-18',
      feedback: 'Great implementation of Dijkstra algorithm. Optimization on adjacency list noted.',
      submissionNote: 'Implemented using C++ STL vector and priority queue.',
    },
    {
      id: 'asg-2',
      title: 'Matrix Proofs & Combinatorics Problem Set',
      courseCode: 'MATH-202',
      courseName: 'MATH-202 Discrete Math',
      dueDate: '2026-08-12',
      totalPoints: 100,
      earnedPoints: 54,
      status: 'Graded',
      submittedAt: '2026-08-12',
      feedback: 'Incomplete proof on structural induction in section B. Revise matrix eigenvalues.',
      submissionNote: 'Attached PDF with handwriting scans.',
    },
    {
      id: 'asg-3',
      title: 'Neural Network Classifier from Scratch',
      courseCode: 'CS-305',
      courseName: 'CS-305 Machine Learning',
      dueDate: '2026-08-25',
      totalPoints: 100,
      earnedPoints: null,
      status: 'Pending',
      submittedAt: null,
      feedback: null,
      submissionNote: '',
    },
    {
      id: 'asg-4',
      title: 'Microservices Architecture Design & Docker Compose',
      courseCode: 'SE-401',
      courseName: 'SE-401 Software Arch',
      dueDate: '2026-08-28',
      totalPoints: 50,
      earnedPoints: null,
      status: 'Pending',
      submittedAt: null,
      feedback: null,
      submissionNote: '',
    },
  ],

  // Student Examinations & Marks
  examinations: [
    {
      id: 'ex-1',
      subject: 'CS-301 Algorithms',
      examType: 'Mid-Semester Exam',
      date: '2026-07-15',
      maxMarks: 100,
      obtainedMarks: 82,
      grade: 'A-',
      classAverage: 74,
    },
    {
      id: 'ex-2',
      subject: 'MATH-202 Discrete Math',
      examType: 'Mid-Semester Exam',
      date: '2026-07-18',
      maxMarks: 100,
      obtainedMarks: 58,
      grade: 'D+',
      classAverage: 71,
    },
    {
      id: 'ex-3',
      subject: 'CS-305 Machine Learning',
      examType: 'Mid-Semester Exam',
      date: '2026-07-22',
      maxMarks: 100,
      obtainedMarks: 88,
      grade: 'A',
      classAverage: 78,
    },
    {
      id: 'ex-4',
      subject: 'SE-401 Software Arch',
      examType: 'Mid-Semester Exam',
      date: '2026-07-25',
      maxMarks: 100,
      obtainedMarks: 91,
      grade: 'A+',
      classAverage: 80,
    },
  ],

  // AI Academic Intelligence Engine Data (Pseudo Map Flow output)
  aiStudentIntelligence: {
    studentId: 'std_101',
    studentName: 'Alex Mercer',
    overallPerformanceScore: 71, // 71%
    metrics: {
      attendancePct: 72,
      assignmentAvg: 81,
      examAvg: 58,
    },
    academicRiskLevel: 'Medium', // Low, Medium, High, Critical
    riskColor: '#f59e0b',
    weakSubjects: [
      {
        subjectCode: 'MATH-202',
        subjectName: 'Discrete Mathematics & Linear Algebra',
        currentScore: 58,
        attendance: 69.2,
        reason: 'Recent examination score declined to 58% while attendance dropped below the 75% mandatory threshold.',
        criticalTopics: ['Eigenvalues & Vector Spaces', 'Structural Induction Proofs', 'Combinatorics'],
      },
    ],
    performanceTrends: [
      { month: 'Mar', attendance: 88, assignments: 85, exams: 75, overall: 82 },
      { month: 'Apr', attendance: 84, assignments: 82, exams: 70, overall: 78 },
      { month: 'May', attendance: 79, assignments: 80, exams: 64, overall: 74 },
      { month: 'Jun', attendance: 75, assignments: 82, exams: 60, overall: 72 },
      { month: 'Jul', attendance: 72, assignments: 81, exams: 58, overall: 71 },
    ],
    aiRecommendations: [
      {
        id: 'rec-1',
        title: 'Prioritize Mathematics Practice',
        category: 'Subject Recovery',
        priority: 'High',
        description: 'Complete 3 problem sets in Eigenvalues and structural proof induction to reverse the recent drop in MATH-202 exam performance.',
        actionableSteps: [
          'Review Chapter 4 (Vector Spaces) lecture recordings.',
          'Schedule a 30-min office hour session with Dr. Robert Vance.',
          'Solve previous year mid-term question bank.',
        ],
      },
      {
        id: 'rec-2',
        title: 'Restore Attendance Level above 75%',
        category: 'Attendance Alert',
        priority: 'Urgent',
        description: 'MATH-202 attendance is currently 69.2%. Attending the next 3 consecutive lectures will restore compliance.',
        actionableSteps: [
          'Attend Mon & Wed 01:00 PM math lectures.',
          'Submit medical/absence justification if applicable.',
        ],
      },
      {
        id: 'rec-3',
        title: 'Maintain Momentum in CS-301 & SE-401',
        category: 'Strength Reinforcement',
        priority: 'Medium',
        description: 'Your Software Architecture and Algorithm scores are in the top 15% of the class. Keep up the consistent submission schedule.',
        actionableSteps: ['Prepare ahead for Neural Network ML assignment.'],
      },
    ],
    teacherInterventionsNeeded: [
      {
        teacherId: 'tch_202',
        teacherName: 'Dr. Robert Vance',
        interventionType: 'Remedial Math Session',
        status: 'Recommended',
        reason: 'Student scored 54% on assignment and 58% on mid-term exam.',
      },
    ],
  },

  // Admin Institutional Insights & Analytics
  adminAnalytics: {
    totalStudents: 1240,
    totalTeachers: 78,
    totalCourses: 56,
    activeClasses: 42,
    campusAcademicHealthIndex: 78.4,
    riskDistribution: {
      low: 820,
      medium: 290,
      high: 95,
      critical: 35,
    },
    departmentPerformance: [
      { department: 'Computer Science', avgScore: 82.4, attendanceAvg: 87.2, riskCount: 14 },
      { department: 'Software Engineering', avgScore: 84.1, attendanceAvg: 89.0, riskCount: 8 },
      { department: 'Artificial Intelligence', avgScore: 81.0, attendanceAvg: 85.5, riskCount: 12 },
      { department: 'Mathematics', avgScore: 68.5, attendanceAvg: 74.2, riskCount: 45 },
      { department: 'Electrical Eng', avgScore: 73.2, attendanceAvg: 78.4, riskCount: 26 },
    ],
    atRiskStudentsList: [
      { id: 'std_103', name: 'Marcus Vance', rollNo: '2026-CS-089', department: 'CS', cgpa: 2.35, riskLevel: 'High', weakSubject: 'Discrete Math', attendance: 62.0 },
      { id: 'std_108', name: 'Daniel Kim', rollNo: '2026-EE-012', department: 'EE', cgpa: 2.10, riskLevel: 'Critical', weakSubject: 'Circuits II', attendance: 54.5 },
      { id: 'std_114', name: 'Chloe Bennett', rollNo: '2026-AI-045', department: 'AI', cgpa: 2.48, riskLevel: 'High', weakSubject: 'Linear Algebra', attendance: 68.0 },
      { id: 'std_120', name: 'Liam O\'Connor', rollNo: '2026-MATH-009', department: 'MATH', cgpa: 1.95, riskLevel: 'Critical', weakSubject: 'Calculus III', attendance: 48.0 },
    ],
    recentActivities: [
      { id: 'act-1', time: '10 mins ago', user: 'Dr. Sarah Jenkins', role: 'Teacher', action: 'Posted Assignment 3 for CS-305 Machine Learning' },
      { id: 'act-2', time: '25 mins ago', user: 'Alex Mercer', role: 'Student', action: 'Submitted Assignment Graph Traversal for CS-301' },
      { id: 'act-3', time: '1 hour ago', user: 'Dr. Robert Vance', role: 'Teacher', action: 'Entered Mid-Term Exam marks for MATH-202' },
      { id: 'act-4', time: '2 hours ago', user: 'System AI Engine', role: 'AI Engine', action: 'Executed campus-wide Academic Risk Analysis scan' },
      { id: 'act-5', time: '3 hours ago', user: 'Admin User', role: 'Admin', action: 'Updated enrollment cap for CS-301 to 50 students' },
    ],
  },
};
